1:
  consumer_key: secret
  consumer_secret: secret
  access_key: secret
  access_secret: secret
  coin_name: eth
  full_name: Ethereum
  increasing_color: "#19cf86"
  decreasing_color: "#cf1962"
2:
  consumer_key: secret
  consumer_secret: secret
  access_key: secret
  access_secret: secret
  coin_name: btc
  full_name: Bitcoin
  increasing_color: "#187ae7"
  decreasing_color: "#e78518"
